server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev

  # 공통 JPA 설정
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JSON 설정
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

# JWT 설정
jwt:
  secret: ${JWT_SECRET:local-development-secret-key}
  expiration: 86400000

# 파일 저장 경로
file:
  upload-dir: ${user.dir}/images

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html