# StackNote Backend Application Configuration

# 공통 설정
spring:
  application:
    name: stacknote-backend
  
  profiles:
    active: dev
  
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# JWT 설정
jwt:
  secret: stacknote-jwt-secret-key-for-development-environment-should-be-changed-in-production
  access-token-validity: 30    # 액세스 토큰 유효기간 (분)
  refresh-token-validity: 120  # 리프레시 토큰 유효기간 (분)

# 앱 설정
app:
  domain: localhost
  secure-cookies: false  # 개발환경에서는 false, 운영에서는 true

# 파일 업로드 경로
file:
  upload:
    path: uploads/

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC